name: test
on:
  push:
jobs:
  test-gpu:
    runs-on: [slurm]
    strategy:
      matrix:
        include:
          - name: NVIDIA A4000
            partition: defq
            gres: gpu:A4000
            cmake_flags: "-DTRIGDX_USE_MKL=1 -DTRIGDX_USE_GPU=1 -DTRIGDX_USE_XSIMD=1 -DCMAKE_CUDA_ARCHITECTURES=86"
          - name: NVIDIA GH200
            partition: ghq
            gres: gpu:GH200
            cmake_flags: "-DTRIGDX_USE_GPU=1 -DTRIGDX_USE_XSIMD=1 -DCMAKE_CUDA_ARCHITECTURES=90a"
    env:
      DEVICE_NAME: ${{ matrix.name }}
      PARTITION_NAME: ${{ matrix.partition }}
      CMAKE_FLAGS: ${{ matrix.cmake_flags }}
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: ${{ matrix.partition }}
          gres: ${{ matrix.gres }}
          time: "00:10:00"
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            if [[ "$PARTITION_NAME" == defq ]]; then
              source /etc/profile.d/modules.sh
              module load spack/20250403
              module load cuda
              module load intel-oneapi-mkl
            fi
            if [[ "$PARTITION_NAME" == defq ]]; then
              source /etc/profile
            fi
            cmake -S . -B ${BUILD_DIR} ${CMAKE_FLAGS}
            make -C ${BUILD_DIR} -j
            ctest --test-dir ${BUILD_DIR} --output-on-failure
            find ${BUILD_DIR}/benchmarks -type f -executable -exec {} \;