name: test
on:
  push:

jobs:
  build:
    runs-on: [slurm]
    strategy:
      matrix:
        include:
          - name: NVIDIA A4000
            partition: defq
            gres: gpu:A4000
            cmake_flags: "-DTRIGDX_USE_MKL=1 -DTRIGDX_USE_GPU=1 -DTRIGDX_USE_XSIMD=1 -DCMAKE_CUDA_ARCHITECTURES=86"
    env:
      DEVICE_NAME: ${{ matrix.name }}
      PARTITION_NAME: ${{ matrix.partition }}
      CMAKE_FLAGS: ${{ matrix.cmake_flags }}
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1
        with:
          partition: ${{ matrix.partition }}
          gres: ${{ matrix.gres }}
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            if [[ "$PARTITION_NAME" == defq ]]; then
              source /etc/profile.d/modules.sh
              module load spack/20250403
              module load cuda
              module load intel-oneapi-mkl
            fi
            if [[ "$PARTITION_NAME" == defq ]]; then
              source /etc/profile
            fi
            cmake -S . -B ${BUILD_DIR} ${CMAKE_FLAGS}
            make -C ${BUILD_DIR} -j
            tar czf "build-${{ matrix.name }}".tar.gz -C "${BUILD_DIR}"
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.name }}
          path: build.tar.gz

  test:
    runs-on: [slurm]
    needs: build
    strategy:
      matrix:
        include:
          - name: NVIDIA A4000
            partition: defq
            gres: gpu:A4000
    env:
      DEVICE_NAME: ${{ matrix.name }}
      PARTITION_NAME: ${{ matrix.partition }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.name }}
      - uses: astron-rd/slurm-action@v1
        with:
          partition: ${{ matrix.partition }}
          gres: ${{ matrix.gres }}
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            tar xzf "build-${{ matrix.name }}".tar.gz -C "${BUILD_DIR}"
            ctest --test-dir ${BUILD_DIR} --output-on-failure

  benchmark:
    runs-on: [slurm]
    needs: build
    strategy:
      matrix:
        include:
          - name: NVIDIA A4000
            partition: defq
            gres: gpu:A4000
    env:
      DEVICE_NAME: ${{ matrix.name }}
      PARTITION_NAME: ${{ matrix.partition }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.name }}
      - uses: astron-rd/slurm-action@v1
        with:
          partition: ${{ matrix.partition }}
          gres: ${{ matrix.gres }}
          commands: |
            BUILD_DIR=$(mktemp -d -t build-XXXXXXXX)
            tar xzf "build-${{ matrix.name }}".tar.gz -C "${BUILD_DIR}"
            find ${BUILD_DIR}/benchmarks -type f -executable -exec {} \;
